let sb=null;
async function loadSB(){if(sb)return sb;if(typeof supabase==="undefined")return null;if(typeof SUPABASE_URL==="undefined"||typeof SUPABASE_ANON_KEY==="undefined")return null;sb=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);return sb}
function safe(v){return String(v??"-").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
function makeId(){return"BJKP-"+Math.random().toString(36).slice(2,8).toUpperCase()}
async function uploadMemberPhoto(file,id){const c=await loadSB();if(!c)throw Error("Supabase connect नहीं है।");if(!file||!file.type.startsWith("image/"))throw Error("कृपया फोटो चुनें।");if(file.size>5242880)throw Error("फोटो 5 MB से छोटी होनी चाहिए।");const ext=(file.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"").toLowerCase()||"jpg";const path=id+"/"+Date.now()+"."+ext;const{error}=await c.storage.from("member-photos").upload(path,file,{upsert:false,contentType:file.type});if(error)throw Error("फोटो upload नहीं हुई: "+error.message);return c.storage.from("member-photos").getPublicUrl(path).data.publicUrl}
async function submitMembership(e){e.preventDefault();const f=new FormData(e.target),r=document.getElementById("result"),id=makeId(),photo=f.get("photo");const d={member_id:id,name:f.get("name")?.trim(),mobile:f.get("mobile")?.trim(),email:f.get("email")?.trim()||null,district:f.get("district")?.trim(),role:f.get("role")?.trim(),status:"pending",photo_url:null};if(!d.name||!d.mobile||!d.district||!photo?.name){r.innerHTML="<p>सभी जरूरी जानकारी और फोटो भरें।</p>";return}const c=await loadSB();if(!c){r.innerHTML="<p>Database connect नहीं है।</p>";return}try{r.innerHTML="<p>फोटो upload हो रही है...</p>";d.photo_url=await uploadMemberPhoto(photo,id);const{error}=await c.from("members").insert([d]);if(error)throw Error(error.message);e.target.reset();document.getElementById("photoPreview").hidden=true;r.innerHTML="<div class='about-grid'><article><h3>आवेदन सफल!</h3><p>Application ID: <b>"+safe(id)+"</b></p><p>Admin approval के बाद Digital ID जारी होगी।</p></article></div>"}catch(x){r.innerHTML="<p>"+safe(x.message)+"</p>"}}
function showDigitalCard(d){const o=document.getElementById("verifyResult"),p=d.photo_url||"",u=location.origin+location.pathname+"?verify="+encodeURIComponent(d.member_id);o.innerHTML='<div class="idcard"><div class="idhead"><img src="images/logo.png"><div><b>भारतीय जन कल्याण पार्टी</b><small>राष्ट्र प्रथम • जन सेवा सर्वोपरि</small></div></div><h3>DIGITAL MEMBER ID CARD</h3><div class="idphoto">'+(p?'<img src="'+safe(p)+'">':"फोटो उपलब्ध नहीं")+'</div><div class="idinfo"><p><span>नाम</span><b>'+safe(d.name)+'</b></p><p><span>Member ID</span><b>'+safe(d.member_id)+'</b></p><p><span>मोबाइल</span><b>'+safe(d.mobile)+'</b></p><p><span>जिला</span><b>'+safe(d.district)+'</b></p><p><span>भूमिका</span><b>'+safe(d.role)+'</b></p><p><span>स्थिति</span><b>✓ APPROVED</b></p></div><div id="memberQRCode"></div></div>';if(typeof QRCode!=="undefined")new QRCode(document.getElementById("memberQRCode"),{text:u,width:100,height:100})}
async function verifyMember(){const id=document.getElementById("verifyId")?.value.trim().toUpperCase(),o=document.getElementById("verifyResult");if(!id){o.innerHTML="<p>Member ID डालें।</p>";return}const c=await loadSB();if(!c){o.innerHTML="<p>Database connect नहीं है।</p>";return}const{data,error}=await c.from("members").select("member_id,name,mobile,email,district,role,status,approved_at,photo_url").eq("member_id",id).maybeSingle();if(error){o.innerHTML="<p>"+safe(error.message)+"</p>";return}if(!data){o.innerHTML="<p>Member ID नहीं मिली।</p>";return}if(data.status!=="approved"){o.innerHTML="<div class='about-grid'><article><h3>BJKP सदस्यता आवेदन</h3><p>नाम: "+safe(data.name)+"</p><p>स्थिति: "+safe(data.status)+"</p><p>Admin approval के बाद Digital ID जारी होगी।</p></article></div>";return}showDigitalCard(data)}
async function adminLogin(){const c=await loadSB(),email=document.getElementById("adminEmail")?.value.trim(),password=document.getElementById("adminPassword")?.value,msg=document.getElementById("loginMsg");if(!c)return;if(msg)msg.textContent="Login हो रहा है...";const{error}=await c.auth.signInWithPassword({email,password});if(error){if(msg)msg.textContent="Login failed: "+error.message;return}document.getElementById("loginBox")?.setAttribute("hidden","");document.getElementById("dashboard")?.removeAttribute("hidden");loadMembers()}
async function adminLogout(){const c=await loadSB();if(c)await c.auth.signOut();location.reload()}
async function loadMembers(){const c=await loadSB();if(!c)return;const{data,error}=await c.from("members").select("*").order("created_at",{ascending:false});if(error)return;const rows=data||[];if(document.getElementById("total"))total.textContent=rows.length;if(document.getElementById("pending"))pending.textContent=rows.filter(x=>x.status==="pending").length;if(document.getElementById("approved"))approved.textContent=rows.filter(x=>x.status==="approved").length;const m=document.getElementById("members");if(!m)return;m.innerHTML=rows.map(x=>'<tr><td>'+safe(x.member_id)+'</td><td>'+safe(x.name)+'</td><td>'+safe(x.mobile)+'</td><td>'+safe(x.district)+'</td><td>'+safe(x.status)+'</td><td>'+(x.status==="pending"?'<button onclick="setStatus(\''+safe(x.member_id)+'\',\'approved\')">Approve</button> <button onclick="setStatus(\''+safe(x.member_id)+'\',\'rejected\')">Reject</button>':"—")+'</td></tr>').join("")}
async function setStatus(id,status){const c=await loadSB();if(!c)return;const{error}=await c.from("members").update({status,approved_at:status==="approved"?new Date().toISOString():null}).eq("member_id",id);if(error){alert(error.message);return}loadMembers()}
function autoVerifyFromURL(){const id=new URLSearchParams(location.search).get("verify");if(id){const i=document.getElementById("verifyId");if(i){i.value=id;setTimeout(verifyMember,400)}}}
document.addEventListener("DOMContentLoaded",()=>{const f=document.getElementById("memberForm");if(f)f.addEventListener("submit",submitMembership);autoVerifyFromURL()});