let sb=null;
async function loadSB(){if(sb)return sb;if(typeof SUPABASE==="undefined")return null;sb=SUPABASE.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);return sb}
function makeId(){return "BJKP-"+Math.random().toString(36).slice(2,8).toUpperCase()}
async function submitMembership(e){e.preventDefault();const f=new FormData(e.target);const data={member_id:makeId(),name:f.get("name"),mobile:f.get("mobile"),email:f.get("email")||null,district:f.get("district"),role:f.get("role"),status:"pending"};const client=await loadSB();if(!client){document.getElementById("result").innerHTML='<p class="error">Database अभी connect नहीं है। पहले config.js में Supabase settings डालें।</p>';return}
const {error}=await client.from("members").insert(data);if(error){document.getElementById("result").innerHTML='<p class="error">आवेदन जमा नहीं हुआ।</p>';return}
e.target.reset();document.getElementById("result").innerHTML='<div class="idcard"><h3>BJKP सदस्यता आवेदन</h3><p>आवेदन सफलतापूर्वक जमा हुआ।</p><p><b>Application ID:</b> '+data.member_id+'</p><p>Admin approval के बाद Digital ID जारी होगी।</p></div>'}
async function verifyMember(){const id=document.getElementById("verifyId").value.trim();const out=document.getElementById("verifyResult");const client=await loadSB();if(!client){out.innerHTML='<p class="error">Database connect नहीं है।</p>';return}const {data,error}=await client.from("members").select("member_id,name,district,role,status,approved_at").eq("member_id",id).single();if(error||!data){out.innerHTML='<p class="error">सदस्य नहीं मिला।</p>';return}if(data.status!=="approved"){out.innerHTML='<p>यह आवेदन अभी approved नहीं है।</p>';return}out.innerHTML='<div class="idcard"><h3>भारतीय जन कल्याण पार्टी</h3><p><b>Digital Member ID:</b> '+data.member_id+'</p><p><b>नाम:</b> '+data.name+'</p><p><b>जिला:</b> '+data.district+'</p><p><b>भूमिका:</b> '+data.role+'</p><p class="success">✓ Approved Member</p></div>'}
async function adminLogin(){const c=await loadSB(),email=document.getElementById("adminEmail").value,pw=document.getElementById("adminPassword").value;if(!c){loginMsg.textContent="Supabase config पहले भरें।";return}const {error}=await c.auth.signInWithPassword({email,password:pw});if(error){loginMsg.textContent="Login failed";return}document.getElementById("loginBox").hidden=true;document.getElementById("dashboard").hidden=false;loadMembers()}
async function adminLogout(){const c=await loadSB();if(c)await c.auth.signOut();location.reload()}
async function loadMembers(){const c=await loadSB();if(!c)return;const {data}=await c.from("members").select("*").order("created_at",{ascending:false});const rows=data||[];total.textContent=rows.length;pending.textContent=rows.filter(x=>x.status==="pending").length;approved.textContent=rows.filter(x=>x.status==="approved").length;members.innerHTML=rows.map(x=>`<tr><td>${x.member_id}</td><td>${x.name}</td><td>${x.mobile}</td><td>${x.district}</td><td>${x.status}</td><td>${x.status==="pending"?`<button class="btn approve" onclick="setStatus('${x.member_id}','approved')">Approve</button> <button class="btn reject" onclick="setStatus('${x.member_id}','rejected')">Reject</button>`:"—"}</td></tr>`).join("")}
async function setStatus(id,status){const c=await loadSB();await c.from("members").update({status,approved_at:status==="approved"?new Date().toISOString():null}).eq("member_id",id);loadMembers()}
document.getElementById("memberForm")?.addEventListener("submit",submitMembership);
