-- BJKP COMPLETE SUPABASE SETUP
-- 1) Supabase Dashboard > SQL Editor > paste/run this file.
-- 2) Authentication > Users में अपना admin user बनाएं (email + password).
-- 3) config.js में Project URL और public anon key डालें.
-- NEVER put the service_role key in the website.

create extension if not exists pgcrypto;

create table if not exists public.site_settings (
  id bigint primary key default 1 check (id=1),
  party_name text default 'भारतीय जन कल्याण पार्टी',
  tagline text default 'जन-जन का विश्वास, राष्ट्र का विकास',
  leader_name text default 'अजीत कुमार',
  leader_role text default 'राष्ट्रीय अध्यक्ष',
  email text default 'bjkporganization@gmail.com',
  phone text default '+91 79062 00000',
  updated_at timestamptz default now()
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  published_at date default current_date,
  created_at timestamptz default now()
);
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  created_at timestamptz default now()
);
create table if not exists public.officers (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  photo_url text,
  created_at timestamptz default now()
);
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text,
  image_url text not null,
  created_at timestamptz default now()
);
create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  title text,
  video_url text not null,
  created_at timestamptz default now()
);
create table if not exists public.memberships (
  id bigint generated by default as identity primary key,
  name text not null,
  mobile text not null,
  district text,
  message text,
  created_at timestamptz default now()
);

alter table public.site_settings enable row level security;
alter table public.news enable row level security;
alter table public.announcements enable row level security;
alter table public.officers enable row level security;
alter table public.gallery enable row level security;
alter table public.videos enable row level security;
alter table public.memberships enable row level security;

-- Public website can read public content.
drop policy if exists "public read news" on public.news;
create policy "public read news" on public.news for select using (true);
drop policy if exists "public read announcements" on public.announcements;
create policy "public read announcements" on public.announcements for select using (true);
drop policy if exists "public read officers" on public.officers;
create policy "public read officers" on public.officers for select using (true);
drop policy if exists "public read gallery" on public.gallery;
create policy "public read gallery" on public.gallery for select using (true);
drop policy if exists "public read videos" on public.videos;
create policy "public read videos" on public.videos for select using (true);
drop policy if exists "public read settings" on public.site_settings;
create policy "public read settings" on public.site_settings for select using (true);

-- Logged-in admin can manage content.
drop policy if exists "auth manage news" on public.news;
create policy "auth manage news" on public.news for all to authenticated using (true) with check (true);
drop policy if exists "auth manage announcements" on public.announcements;
create policy "auth manage announcements" on public.announcements for all to authenticated using (true) with check (true);
drop policy if exists "auth manage officers" on public.officers;
create policy "auth manage officers" on public.officers for all to authenticated using (true) with check (true);
drop policy if exists "auth manage gallery" on public.gallery;
create policy "auth manage gallery" on public.gallery for all to authenticated using (true) with check (true);
drop policy if exists "auth manage videos" on public.videos;
create policy "auth manage videos" on public.videos for all to authenticated using (true) with check (true);
drop policy if exists "auth manage settings" on public.site_settings;
create policy "auth manage settings" on public.site_settings for all to authenticated using (true) with check (true);

-- Public visitors can submit membership forms, but cannot read them.
drop policy if exists "public submit membership" on public.memberships;
create policy "public submit membership" on public.memberships for insert to anon,authenticated with check (true);
drop policy if exists "auth manage memberships" on public.memberships;
create policy "auth manage memberships" on public.memberships for all to authenticated using (true) with check (true);

insert into public.site_settings(id) values(1) on conflict (id) do nothing;

-- Optional seed content
insert into public.news(title,published_at) values
('BJKP की जिला स्तरीय बैठक सम्पन्न', current_date),
('युवा सम्मेलन में भारी जनभागीदारी', current_date - 3),
('स्वच्छ भारत अभियान में BJKP की भागीदारी', current_date - 7)
on conflict do nothing;

insert into public.announcements(title) values
('राष्ट्रीय कार्यकारिणी की महत्वपूर्ण बैठक'),
('सदस्यता अभियान की शुरुआत'),
('युवा नेतृत्व प्रशिक्षण शिविर')
on conflict do nothing;
